"""initial tables

Revision ID: 06b65800aad6
Revises: 
Create Date: 2026-04-15 16:49:30.487478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b65800aad6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('art_direction', sa.JSON(), nullable=True),
    sa.Column('script_raw_text', sa.Text(), nullable=False),
    sa.Column('voiceover_audio_url', sa.String(length=512), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('export_format', sa.String(length=30), nullable=False),
    sa.Column('include_vector', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('include_masks', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('layer_naming_convention', sa.String(length=100), nullable=True),
    sa.Column('export_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='queued', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('script_excerpt', sa.Text(), nullable=True),
    sa.Column('visual_description', sa.Text(), nullable=True),
    sa.Column('intention', sa.String(length=255), nullable=True),
    sa.Column('shot_type', sa.String(length=100), nullable=True),
    sa.Column('characters', sa.JSON(), nullable=True),
    sa.Column('objects', sa.JSON(), nullable=True),
    sa.Column('background', sa.String(length=255), nullable=True),
    sa.Column('prompt_generated', sa.Text(), nullable=True),
    sa.Column('image_generation_params', sa.JSON(), nullable=True),
    sa.Column('generated_image_url', sa.String(length=512), nullable=True),
    sa.Column('user_validated_image_url', sa.String(length=512), nullable=True),
    sa.Column('user_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('image_status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('segmentation_status', sa.String(length=30), nullable=True),
    sa.Column('vectorization_status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('mask_url', sa.String(length=512), nullable=True),
    sa.Column('original_png_url', sa.String(length=512), nullable=True),
    sa.Column('svg_url', sa.String(length=512), nullable=True),
    sa.Column('layer_name', sa.String(length=100), nullable=True),
    sa.Column('transform_data', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('user_approved', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('replicate_prediction_id', sa.String(length=255), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='queued', nullable=False),
    sa.Column('result_image_url', sa.String(length=512), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segmentation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scene_id', sa.UUID(), nullable=False),
    sa.Column('source_image_url', sa.String(length=512), nullable=True),
    sa.Column('sam_model_version', sa.String(length=100), nullable=True),
    sa.Column('mediapipe_pose_used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='queued', nullable=False),
    sa.Column('result_asset_ids', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vectorization_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('tool', sa.String(length=50), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='queued', nullable=False),
    sa.Column('svg_result_url', sa.String(length=512), nullable=True),
    sa.Column('vector_quality_score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vectorization_jobs')
    op.drop_table('segmentation_jobs')
    op.drop_table('generation_jobs')
    op.drop_table('assets')
    op.drop_table('scenes')
    op.drop_table('export_batches')
    op.drop_table('projects')
    # ### end Alembic commands ###
